databases:
  - name: agroshare-db
    databaseName: agroshare
    user: agroshare
    plan: free

services:
  - type: web
    name: agroshare-api
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: agroshare-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://agroshare-frontend.onrender.com,https://agroshare-api-g7ze.onrender.com
      - key: EXPOSE_API_DOCS
        value: "false"
      - key: PAYSTACK_WEBHOOK_SECRET
        generateValue: true
      - key: AFRICASTALKING_USERNAME
        value: sandbox
      - key: AFRICASTALKING_API_KEY
        value: atsk_cc7f056bd3b7980235fada6ea1e3f24d80ba5df0aae7cdb71a4f4c52e7beb22e5f00e6aa
      - key: AFRICASTALKING_SENDER_ID
        value: "SANDBOX"
      - key: SMS_PROVIDER
        value: africastalking

  - type: web
    name: agroshare-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: REACT_APP_API_BASE
        value: https://agroshare-api-g7ze.onrender.com/api
      - key: REACT_APP_ENVIRONMENT
        value: production